services:

  db:
    image: mysql:8.0.33
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: fitness_db
      MYSQL_USER: fitness
      MYSQL_PASSWORD: pass
    ports:
      - 3306:3306
  php:
    container_name: php
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www/symfony_app

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/symfony_app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
